<template>
  <div class="application-admin-page">
    <div class="page-header"><div><h2 class="page-title">立项申请管理</h2><p class="page-desc">管理申请批次、材料合格性审核、学校报送与正式结果；校内审核不代表学校批准。</p></div><div class="page-actions"><el-button :loading="loading" @click="loadAll"><el-icon><Refresh /></el-icon>刷新</el-button><el-button type="primary" @click="openBatchDialog"><el-icon><Plus /></el-icon>新建批次</el-button></div></div>
    <el-alert title="本页“材料合格”仅指申报材料满足校内报送要求。正式立项以学校反馈结果为准。" type="warning" show-icon :closable="false" />
    <el-tabs v-model="tab" class="section">
      <el-tab-pane label="批次与统计" name="batches">
        <div class="panel"><el-table v-loading="loading" :data="batches" class="desktop-table" empty-text="暂无立项批次"><el-table-column prop="batchName" label="批次" min-width="190" /><el-table-column prop="applicationYear" label="年度" width="80" /><el-table-column prop="approvalRound" label="节点" width="100"><template #default="{row}">{{ roundLabel(row.approvalRound) }}</template></el-table-column><el-table-column prop="status" label="状态" width="100"><template #default="{row}"><el-tag :type="batchType(row.status)">{{ batchStatus(row.status) }}</el-tag></template></el-table-column><el-table-column label="统计" min-width="220"><template #default="{row}">申请 {{ Number(row.applicationCount) }} · 待审 {{ Number(row.pendingReviewCount) }} · 合格 {{ Number(row.eligibleCount) }} · 已转项目 {{ Number(row.convertedCount) }}</template></el-table-column><el-table-column label="操作" width="390" fixed="right"><template #default="{row}"><el-button v-if="!row.isHistorical" text @click="openTemplates(row)">材料模板</el-button><el-button v-if="row.status==='draft' && !row.isHistorical" text type="success" @click="changeBatchStatus(row,'open')">开放</el-button><el-button v-if="row.status==='open'" text @click="changeBatchStatus(row,'closed')">关闭</el-button><el-button v-if="row.status==='closed' && !row.isHistorical" text @click="changeBatchStatus(row,'open')">重新开放</el-button><el-button v-if="['open','closed'].includes(row.status) && Number(row.eligibleCount)" text type="primary" @click="exportBatch(row)">冻结并报送</el-button><el-button v-if="row.status==='reported' || row.isHistorical" text type="warning" @click="openResult(row)">{{ row.isHistorical ? '导入历史正式名单' : '导入学校结果' }}</el-button></template></el-table-column></el-table></div>
      </el-tab-pane>
      <el-tab-pane label="材料合格性审核" name="reviews">
        <div class="toolbar panel"><div class="filters"><el-select v-model="filters.batchId" clearable placeholder="全部批次" @change="loadApplications"><el-option v-for="item in batches" :key="item.id" :label="item.batchName" :value="item.id" /></el-select><el-select v-model="filters.status" clearable placeholder="全部状态" @change="loadApplications"><el-option label="待审核" value="submitted" /><el-option label="材料合格" value="eligible" /><el-option label="已退回" value="returned" /><el-option label="已冻结" value="frozen" /></el-select></div></div>
        <div class="panel"><el-table v-loading="applicationsLoading" :data="applications" class="desktop-table" empty-text="暂无申请"><el-table-column prop="applicantName" label="申请人" width="110" /><el-table-column prop="studentNo" label="学号" width="145" /><el-table-column prop="college" label="学院" min-width="150" /><el-table-column prop="batchName" label="批次" min-width="170" /><el-table-column prop="submissionVersion" label="版本" width="70"><template #default="{row}">V{{ row.submissionVersion }}</template></el-table-column><el-table-column prop="status" label="状态" width="120"><template #default="{row}"><el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="250" fixed="right"><template #default="{row}"><el-button text @click="showMaterials(row)">材料版本</el-button><el-button v-if="row.status==='submitted'" text type="success" @click="review(row,'eligible')">材料合格</el-button><el-button v-if="row.status==='submitted'" text type="danger" @click="review(row,'returned')">退回</el-button></template></el-table-column></el-table><div class="pagination-row" v-if="pagination.total"><el-pagination v-model:current-page="pagination.page" :page-size="pagination.pageSize" :total="pagination.total" layout="total,prev,pager,next" @current-change="loadApplications" /></div></div>
      </el-tab-pane>
      <el-tab-pane label="报送批次与学校结果" name="exports">
        <div class="panel"><el-table :data="exports" empty-text="暂无报送批次"><el-table-column prop="exportNo" label="报送编号" min-width="200" /><el-table-column prop="batchName" label="申请批次" min-width="180" /><el-table-column prop="applicationCount" label="冻结申请" width="100" /><el-table-column prop="status" label="状态" width="100" /><el-table-column prop="createdAt" label="导出时间" width="170"><template #default="{row}">{{ formatTime(row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="300"><template #default="{row}"><el-button v-if="row.status==='ready'" text @click="downloadExport(row,'workbook')">Excel</el-button><el-button v-if="row.status==='ready'" text @click="downloadExport(row,'package')">材料包</el-button><el-button v-if="row.status==='ready'" text type="danger" @click="recall(row)">撤回报送</el-button></template></el-table-column></el-table></div>
      </el-tab-pane>
    </el-tabs>

    <el-dialog v-model="batchVisible" title="新建立项批次" width="820px"><el-form label-position="top"><div class="form-grid"><el-form-item label="批次名称"><el-input v-model="batchForm.batchName" /></el-form-item><el-form-item label="年度"><el-input-number v-model="batchForm.applicationYear" :min="2000" :max="2100" style="width:100%" /></el-form-item><el-form-item label="节点"><el-select v-model="batchForm.approvalRound" style="width:100%"><el-option label="首次立项" value="first" /><el-option label="补充立项" value="supplement" /></el-select></el-form-item><el-form-item label="截止时间"><el-date-picker v-model="batchForm.deadlineAt" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" style="width:100%" :disabled="batchForm.isHistorical" /></el-form-item></div><el-form-item><el-checkbox v-model="batchForm.isHistorical" @change="historyChanged">这是已完成的历史首次立项批次（不向申请人开放）</el-checkbox></el-form-item><el-divider content-position="left">申请字段</el-divider><div v-for="(field,index) in batchForm.applicationSchema" :key="index" class="config-row"><el-input v-model="field.key" placeholder="字段 key" /><el-input v-model="field.label" placeholder="显示名称" /><el-select v-model="field.type"><el-option label="单行文本" value="text" /><el-option label="多行文本" value="textarea" /><el-option label="数字" value="number" /><el-option label="日期" value="date" /></el-select><el-checkbox v-model="field.required">必填</el-checkbox><el-button text type="danger" @click="batchForm.applicationSchema.splice(index,1)">删除</el-button></div><el-button text type="primary" @click="batchForm.applicationSchema.push({key:'',label:'',type:'text',required:false,options:[]})">+ 添加字段</el-button><el-divider content-position="left">必交材料与文件规则</el-divider><div v-for="(item,index) in batchForm.materialRequirements" :key="index" class="config-row requirement-row"><el-input v-model="item.code" placeholder="材料编码" /><el-input v-model="item.name" placeholder="材料名称" /><el-select v-model="item.allowedExtensions" multiple collapse-tags><el-option v-for="ext in extensions" :key="ext" :value="ext" /></el-select><el-input-number v-model="item.maxFileMb" :min="1" :max="50" /><el-checkbox v-model="item.required">必交</el-checkbox><el-button text type="danger" @click="batchForm.materialRequirements.splice(index,1)">删除</el-button></div><el-button text type="primary" @click="batchForm.materialRequirements.push({code:'',name:'',allowedExtensions:['pdf'],maxFileMb:20,required:true})">+ 添加材料</el-button></el-form><template #footer><el-button @click="batchVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="createBatch">保存草稿</el-button></template></el-dialog>

    <el-dialog v-model="materialsVisible" :title="selectedApplication ? `${selectedApplication.applicantName} · 材料版本` : '材料版本'" width="860px"><el-table v-loading="materialsLoading" :data="materialFiles" empty-text="暂无材料"><el-table-column prop="submissionVersion" label="提交版本" width="90"><template #default="{row}">V{{row.submissionVersion}}</template></el-table-column><el-table-column prop="fileVersion" label="文件版本" width="90" /><el-table-column prop="originalName" label="文件名" min-width="220" /><el-table-column prop="fileSize" label="大小" width="100"><template #default="{row}">{{formatSize(row.fileSize)}}</template></el-table-column><el-table-column prop="sha256" label="SHA-256" min-width="180" show-overflow-tooltip /><el-table-column label="操作" width="80"><template #default="{row}"><el-button text @click="downloadMaterial(row)">下载</el-button></template></el-table-column></el-table></el-dialog>

    <el-dialog v-model="templatesVisible" :title="templateBatch ? `${templateBatch.batchName} · 材料模板` : '材料模板'" width="720px"><el-alert title="模板更新会写入审计事件；已提交的申请材料版本不受影响。" type="info" :closable="false" show-icon /><div v-for="item in templateRequirements" :key="item.id" class="application-upload-row"><div><strong>{{item.name}}</strong><p>{{item.description || '未填写说明'}}</p><p v-if="item.templateOriginalName">当前模板：{{item.templateOriginalName}} · SHA-256 {{item.templateSha256}}</p><p v-else>当前未提供模板</p></div><input type="file" @change="uploadTemplate(item,$event)" /></div></el-dialog>

    <el-dialog v-model="resultVisible" :title="resultBatch?.isHistorical ? '历史首次立项正式名单预检查' : '学校反馈结果预检查'" width="620px"><el-alert :title="resultBatch?.isHistorical ? '历史缺失材料将明确记为 missing_historical，不生成虚假材料记录。' : '先预检查，不修改项目；确认提交时整批事务执行。'" type="info" :closable="false" show-icon /><el-radio-group v-if="!resultBatch?.isHistorical" v-model="resultMode" class="section"><el-radio-button value="file">上传学校反馈文件</el-radio-button><el-radio-button value="manual">逐条录入</el-radio-button></el-radio-group><div v-if="resultMode==='file' || resultBatch?.isHistorical" class="official-upload section"><input type="file" accept=".xlsx" @change="resultFile=$event.target.files?.[0] || null" /><el-button type="primary" :disabled="!resultFile" :loading="validating" @click="validateResult">上传并预检查</el-button></div><el-form v-else label-position="top" class="section"><div class="form-grid"><el-form-item label="学号"><el-input v-model.trim="manualResult.studentNo" /></el-form-item><el-form-item label="学校结果"><el-select v-model="manualResult.result" style="width:100%"><el-option label="通过" value="approved" /><el-option label="未通过" value="rejected" /></el-select></el-form-item><el-form-item label="项目编号（通过时必填）"><el-input v-model.trim="manualResult.projectCode" /></el-form-item><el-form-item label="立项日期"><el-date-picker v-model="manualResult.approvalDate" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></div><el-form-item label="学校反馈备注"><el-input v-model.trim="manualResult.remark" type="textarea" :rows="3" /></el-form-item><el-button type="primary" :loading="validating" @click="validateManualResult">逐条预检查</el-button></el-form><el-alert v-if="validation" :title="validation.valid ? `预检查通过，共 ${validation.totalRows} 行` : `发现 ${validation.errorCount} 个问题`" :type="validation.valid ? 'success' : 'error'" show-icon :closable="false" /><div v-if="validation?.errors?.length" class="validation-errors"><p v-for="error in validation.errors" :key="`${error.row}-${error.field}`">第 {{error.row}} 行 {{error.field}}：{{error.message}}</p></div><template #footer><el-button @click="resultVisible=false">关闭</el-button><el-button v-if="validation?.valid" type="success" :loading="committing" @click="commitResult">确认导入并处理项目</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { apiRequest, downloadFile } from '../../services/http'
const tab=ref('batches'), loading=ref(false), saving=ref(false), batches=ref([]), exports=ref([])
const applications=ref([]), applicationsLoading=ref(false), pagination=reactive({page:1,pageSize:20,total:0}), filters=reactive({batchId:null,status:'submitted'})
const batchVisible=ref(false), materialsVisible=ref(false), materialsLoading=ref(false), materialFiles=ref([]), selectedApplication=ref(null)
const templatesVisible=ref(false), templateBatch=ref(null), templateRequirements=ref([])
const resultVisible=ref(false), resultBatch=ref(null), resultFile=ref(null), validation=ref(null), validating=ref(false), committing=ref(false), resultMode=ref('file')
const manualResult=reactive({studentNo:'',result:'approved',projectCode:'',approvalDate:'',remark:''})
const extensions=['pdf','doc','docx','xls','xlsx','ppt','pptx','jpg','jpeg','png','zip']
const newBatch=()=>({batchName:'',applicationYear:new Date().getFullYear(),approvalRound:'supplement',deadlineAt:'',isHistorical:false,applicationSchema:[{key:'title',label:'项目名称',type:'text',required:true,options:[]},{key:'category',label:'项目类别',type:'text',required:true,options:[]},{key:'projectGroup',label:'申报组别',type:'text',required:false,options:[]}],materialRequirements:[{code:'application_form',name:'项目申报书',allowedExtensions:['pdf','docx'],maxFileMb:20,required:true},{code:'team_roster',name:'团队成员表',allowedExtensions:['xlsx'],maxFileMb:10,required:true}]})
const batchForm=reactive(newBatch())
const roundLabel=v=>v==='first'?'首次立项':'补充立项', batchStatus=v=>({draft:'草稿',open:'开放申请',closed:'已关闭',reported:'已报送冻结',completed:'已完成'}[v]||v), batchType=v=>({open:'success',reported:'warning',completed:'success'}[v]||'info')
const statusLabel=v=>({submitted:'待材料合格性审核',eligible:'材料合格',returned:'已退回',frozen:'已冻结报送',converted:'已转正式项目',school_rejected:'学校未通过'}[v]||v), statusType=v=>({submitted:'warning',eligible:'success',returned:'danger',frozen:'warning',converted:'success',school_rejected:'danger'}[v]||'info')
const formatTime=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'-', formatSize=b=>Number(b)<1048576?`${(Number(b)/1024).toFixed(1)} KB`:`${(Number(b)/1048576).toFixed(1)} MB`
async function loadAll(){loading.value=true;try{const [b,e]=await Promise.all([apiRequest('/applications/batches'),apiRequest('/applications/exports')]);batches.value=b.data;exports.value=e.data;await loadApplications()}catch(err){ElMessage.error(err.message)}finally{loading.value=false}}
async function loadApplications(){applicationsLoading.value=true;try{const q=new URLSearchParams({page:pagination.page,pageSize:pagination.pageSize});if(filters.batchId)q.set('batchId',filters.batchId);if(filters.status)q.set('status',filters.status);const r=await apiRequest(`/applications?${q}`);applications.value=r.data;Object.assign(pagination,r.pagination)}catch(e){ElMessage.error(e.message)}finally{applicationsLoading.value=false}}
function openBatchDialog(){Object.assign(batchForm,newBatch());batchVisible.value=true} function historyChanged(v){if(v){batchForm.approvalRound='first';batchForm.deadlineAt='';batchForm.applicationSchema=[];batchForm.materialRequirements=[]}}
async function createBatch(){if(!batchForm.batchName)return ElMessage.warning('请填写批次名称');saving.value=true;try{await apiRequest('/applications/batches',{method:'POST',body:batchForm});ElMessage.success('批次草稿已创建');batchVisible.value=false;loadAll()}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
async function changeBatchStatus(row,status){try{await apiRequest(`/applications/batches/${row.id}/status`,{method:'PATCH',body:{status}});ElMessage.success('批次状态已更新');loadAll()}catch(e){ElMessage.error(e.message)}}
async function review(row,result){try{let reason='';if(result==='returned'){const prompt=await ElMessageBox.prompt('请填写明确、可执行的材料退回原因','退回材料',{inputType:'textarea'});reason=prompt.value}else await ElMessageBox.confirm('确认材料符合校内报送要求？此操作不代表学校批准立项。','材料合格性审核',{type:'warning'});await apiRequest(`/applications/${row.id}/review`,{method:'POST',body:{result,reason}});ElMessage.success(result==='eligible'?'已标记材料合格':'已退回申请人');loadAll()}catch(e){if(e!=='cancel')ElMessage.error(e.message||'审核失败')}}
async function showMaterials(row){selectedApplication.value=row;materialsVisible.value=true;materialsLoading.value=true;try{materialFiles.value=(await apiRequest(`/applications/${row.id}/materials`)).data.files}catch(e){ElMessage.error(e.message)}finally{materialsLoading.value=false}}
async function downloadMaterial(file){try{await downloadFile(`/applications/${selectedApplication.value.id}/materials/${file.id}/download`,file.originalName)}catch(e){ElMessage.error(e.message)}}
async function openTemplates(row){templateBatch.value=row;try{templateRequirements.value=(await apiRequest(`/applications/batches/${row.id}`)).data.materialRequirements;templatesVisible.value=true}catch(e){ElMessage.error(e.message)}}
async function uploadTemplate(item,event){const file=event.target.files?.[0];if(!file)return;try{const body=new FormData();body.append('file',file);await apiRequest(`/applications/batches/${templateBatch.value.id}/requirements/${item.id}/template`,{method:'POST',body});ElMessage.success('模板已上传并记录校验值');await openTemplates(templateBatch.value)}catch(e){ElMessage.error(e.message)}finally{event.target.value=''}}
async function exportBatch(row){try{await ElMessageBox.confirm('导出会冻结所有材料合格申请，冻结后申请人不能修改。','冻结并生成学校报送批次',{type:'warning'});const r=await apiRequest(`/applications/batches/${row.id}/export`,{method:'POST'});ElMessage.success(`已冻结 ${r.data.applicationCount} 份申请并生成材料包`);tab.value='exports';loadAll()}catch(e){if(e!=='cancel')ElMessage.error(e.message||'导出失败')}}
async function downloadExport(row,kind){try{await downloadFile(`/applications/exports/${row.id}/download/${kind}`,kind==='workbook'?`${row.exportNo}.xlsx`:`${row.exportNo}.zip`)}catch(e){ElMessage.error(e.message)}}
async function recall(row){try{const {value}=await ElMessageBox.prompt('撤回已冻结报送必须填写原因','撤回报送',{inputType:'textarea',inputValidator:v=>Boolean(v?.trim())||'原因不能为空'});await apiRequest(`/applications/exports/${row.id}/recall`,{method:'POST',body:{reason:value}});ElMessage.success('报送已撤回并记录审计事件');loadAll()}catch(e){if(e!=='cancel')ElMessage.error(e.message||'撤回失败')}}
function openResult(row){resultBatch.value=row;resultFile.value=null;validation.value=null;resultMode.value='file';Object.assign(manualResult,{studentNo:'',result:'approved',projectCode:'',approvalDate:'',remark:''});resultVisible.value=true}
async function validateResult(){validating.value=true;try{const body=new FormData();body.append('file',resultFile.value);validation.value=(await apiRequest(`/applications/batches/${resultBatch.value.id}/results/validate`,{method:'POST',body})).data;ElMessage[validation.value.valid?'success':'warning'](validation.value.valid?'预检查通过':'请修正错误后重新上传')}catch(e){ElMessage.error(e.message)}finally{validating.value=false}}
async function validateManualResult(){validating.value=true;try{validation.value=(await apiRequest(`/applications/batches/${resultBatch.value.id}/results/manual`,{method:'POST',body:manualResult})).data;ElMessage.success('逐条结果预检查通过')}catch(e){ElMessage.error(e.message)}finally{validating.value=false}}
async function commitResult(){committing.value=true;try{const r=await apiRequest(`/applications/result-imports/${validation.value.importId}/commit`,{method:'POST'});ElMessage.success(`导入完成：通过 ${r.data.approved}，未通过 ${r.data.rejected}`);resultVisible.value=false;loadAll()}catch(e){ElMessage.error(e.message)}finally{committing.value=false}}
onMounted(loadAll)
</script>
