<template>
  <div>
    <div class="page-header"><div><h2 class="page-title">项目变更审批</h2><p class="page-desc">查看证明、前后快照并处理分配给自己的变更材料；超级管理员可查看全部。</p></div><div class="page-actions"><el-button @click="exportRows">导出 Excel</el-button><el-button v-if="isSuper" type="danger" plain @click="openForced">强制负责人变更</el-button></div></div>
    <div class="panel"><div class="toolbar"><div class="filters"><el-select v-model="status" clearable placeholder="导出/审核状态" @change="load"><el-option label="待审核" value="submitted"/><el-option label="已通过" value="approved"/><el-option label="已退回" value="returned"/></el-select><el-input v-model="keyword" clearable placeholder="项目、申请人" @keyup.enter="load"/><el-button @click="load">查询</el-button></div></div>
      <el-table v-loading="loading" :data="items" empty-text="暂无项目变更申请"><el-table-column label="项目 / 申请人" min-width="240"><template #default="{row}"><strong>{{ row.projectTitle }}</strong><div class="table-subline">{{ row.projectCode }} · {{ row.initiatorName }}</div></template></el-table-column><el-table-column prop="changeSummary" label="变更摘要" min-width="320"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="审核分配" width="120"><template #default="{row}">{{ row.assignedTo?'已分配':'未分配' }}</template></el-table-column><el-table-column label="操作" width="210"><template #default="{row}"><el-button text @click="showDetail(row)">证明与对比</el-button><template v-if="row.status==='submitted'&&canReview(row)"><el-button text type="success" @click="review(row,'approve')">通过</el-button><el-button text type="danger" @click="review(row,'return')">退回</el-button></template></template></el-table-column></el-table>
    </div>
    <el-dialog v-model="detailDialog" title="证明文件与变更前后对比" width="900px"><template v-if="detail"><el-alert :title="detail.changeSummary" type="info" :closable="false"/><el-descriptions :column="2" border class="section"><el-descriptions-item label="项目">{{detail.projectCode}} · {{detail.projectTitle}}</el-descriptions-item><el-descriptions-item label="申请人">{{detail.initiatorName}}</el-descriptions-item><el-descriptions-item label="发起方式">{{detail.initiatorType==='forced_admin'?'超级管理员强制发起':'当前负责人发起'}}</el-descriptions-item><el-descriptions-item label="版本">V{{detail.currentVersion}}</el-descriptions-item><el-descriptions-item v-if="detail.forcedReason" label="强制依据说明" :span="2">{{detail.forcedReason}}</el-descriptions-item></el-descriptions><el-table :data="proofFiles"><el-table-column prop="originalName" label="证明文件"/><el-table-column prop="fileSize" label="大小" width="120"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button text type="primary" @click="downloadProof(row)">下载</el-button></template></el-table-column></el-table><el-divider content-position="left">冻结的变更前快照</el-divider><el-table :data="frozenPeople"><el-table-column prop="role" label="角色" width="100"/><el-table-column prop="name" label="姓名"/><el-table-column prop="identifier" label="学号/工号"/><el-table-column prop="organization" label="学院/单位"/></el-table><el-divider content-position="left">拟变更方案</el-divider><pre class="change-json">{{ prettyPlan(detail.proposedChanges) }}</pre></template></el-dialog>
    <el-dialog v-model="forcedDialog" title="超级管理员强制负责人变更" width="720px"><el-alert title="仅用于现负责人无法操作；必须上传依据并留下审批记录，不会直接生效。" type="warning" show-icon :closable="false"/><el-form label-position="top" class="section"><el-form-item label="任务与项目" required><el-select v-model="forced.optionKey" filterable style="width:100%"><el-option v-for="i in options.tasks" :key="keyOf(i)" :value="keyOf(i)" :label="`${i.taskName}｜${i.projectCode} ${i.projectTitle}`"/></el-select></el-form-item><el-form-item label="新负责人" required><el-select v-model="forced.newOwnerPersonId" filterable style="width:100%"><el-option v-for="p in candidates" :key="p.id" :value="p.id" :label="`${p.name}（${p.identifier}）`"/></el-select></el-form-item><el-form-item label="原负责人去向"><el-radio-group v-model="forced.disposition"><el-radio value="member">转为普通成员</el-radio><el-radio value="exit">退出项目</el-radio></el-radio-group></el-form-item><el-form-item label="强制变更原因" required><el-input v-model="forced.reason" type="textarea" maxlength="1000" show-word-limit/></el-form-item><el-form-item label="依据文件" required><el-upload action="#" :auto-upload="false" :limit="1" :on-change="f=>forced.proof=f.raw"><el-button>选择依据文件</el-button></el-upload></el-form-item></el-form><template #footer><el-button @click="forcedDialog=false">取消</el-button><el-button type="danger" :loading="saving" @click="submitForced">提交待审批记录</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue'
import { ElMessage,ElMessageBox } from 'element-plus'
import { apiRequest,downloadFile } from '../../services/http'
import { authStore } from '../../stores/auth'
const loading=ref(false),saving=ref(false),items=ref([]),status=ref('submitted'),keyword=ref(''),detailDialog=ref(false),detail=ref(null),proofFiles=ref([]),forcedDialog=ref(false)
const options=reactive({tasks:[],students:[],teachers:[]}),forced=reactive({optionKey:'',newOwnerPersonId:null,disposition:'member',reason:'',proof:null})
const isSuper=computed(()=>authStore.isSuperAdmin()),candidates=computed(()=>options.students.filter(p=>p.userId&&p.userStatus==='enabled'&&p.accountStatus!=='disabled'))
const keyOf=i=>`${i.taskId}:${i.projectId}`,selectedForced=computed(()=>options.tasks.find(i=>keyOf(i)===forced.optionKey))
const statusLabel=s=>({draft:'草稿',submitted:'待审核',returned:'已退回',approved:'已通过'}[s]||s),statusType=s=>({submitted:'warning',returned:'danger',approved:'success'}[s]||'info')
const canReview=row=>isSuper.value||Number(row.assignedTo)===Number(authStore.state.user?.id)
async function load(){loading.value=true;try{const q=new URLSearchParams({pageSize:100});if(status.value)q.set('status',status.value);if(keyword.value)q.set('keyword',keyword.value);items.value=(await apiRequest(`/project-changes?${q}`)).data}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
async function showDetail(row){try{detail.value=(await apiRequest(`/project-changes/${row.id}`)).data;proofFiles.value=detail.value.latestSubmissionId?(await apiRequest(`/submissions/${detail.value.latestSubmissionId}/files`)).data:[];detailDialog.value=true}catch(e){ElMessage.error(e.message)}}
const frozenPeople=computed(()=>detail.value?.versions?.[0]?.beforeSnapshot?.participations||[])
function prettyPlan(p){const lines=[];if(p.members?.addPersonIds?.length)lines.push(`新增成员：${names(p.members.addPersonIds)}`);if(p.members?.removePersonIds?.length)lines.push(`移除成员：${names(p.members.removePersonIds)}`);if(p.advisors?.addPersonIds?.length)lines.push(`新增导师：${names(p.advisors.addPersonIds)}`);if(p.advisors?.removePersonIds?.length)lines.push(`移除导师：${names(p.advisors.removePersonIds)}`);if(p.ownerChange)lines.push(`新负责人：${names([p.ownerChange.newOwnerPersonId])}\n原负责人：${p.ownerChange.previousOwnerDisposition==='member'?'转为普通成员':'退出项目'}`);return lines.join('\n')}
function names(ids){const all=[...options.students,...options.teachers];return ids.map(id=>all.find(p=>Number(p.id)===Number(id))?.name||`人员#${id}`).join('、')}
async function review(row,action){try{let reason='';if(action==='return')reason=await ElMessageBox.prompt('请填写明确退回原因','退回变更申请',{inputValidator:v=>Boolean(v?.trim()),inputErrorMessage:'退回原因不能为空'}).then(r=>r.value);else await ElMessageBox.confirm('通过后将立即更新项目人员关系并转换负责人账号权限，是否继续？','确认生效',{type:'warning'});await apiRequest(`/submissions/${row.latestSubmissionId}/review`,{method:'PATCH',body:{action,reason,assignmentVersion:row.assignmentVersion}});ElMessage.success(action==='approve'?'变更已审核通过并生效':'变更申请已退回');await load()}catch(e){if(e!=='cancel')ElMessage.error(e.message||'操作失败')}}
async function downloadProof(file){try{await downloadFile(`/submissions/${detail.value.latestSubmissionId}/files/${file.id}/download`,file.originalName)}catch(e){ElMessage.error(e.message)}}
function exportRows(){const q=status.value?`?status=${status.value}`:'';downloadFile(`/project-changes/export${q}`,'项目变更申请.xlsx').catch(e=>ElMessage.error(e.message))}
async function loadOptions(){try{Object.assign(options,(await apiRequest('/project-changes/options')).data)}catch(e){ElMessage.error(e.message)}}
function openForced(){Object.assign(forced,{optionKey:options.tasks[0]?keyOf(options.tasks[0]):'',newOwnerPersonId:null,disposition:'member',reason:'',proof:null});forcedDialog.value=true}
async function submitForced(){if(!selectedForced.value||!forced.newOwnerPersonId||!forced.reason.trim()||!forced.proof)return ElMessage.warning('请完整填写强制变更信息并上传依据');saving.value=true;try{const plan={members:{addPersonIds:[],removePersonIds:[]},advisors:{addPersonIds:[],removePersonIds:[]},ownerChange:{newOwnerPersonId:forced.newOwnerPersonId,previousOwnerDisposition:forced.disposition}};const id=(await apiRequest('/project-changes',{method:'POST',body:{taskId:selectedForced.value.taskId,projectId:selectedForced.value.projectId,forcedReason:forced.reason,proposedChanges:plan}})).data.id;const body=new FormData();body.append('file',forced.proof);await apiRequest(`/project-changes/${id}/proof`,{method:'POST',body});await apiRequest(`/project-changes/${id}/submit`,{method:'POST'});ElMessage.success('强制变更已形成待审批记录，尚未直接生效');forcedDialog.value=false;await load()}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
onMounted(()=>Promise.all([load(),loadOptions()]))
</script>
<style scoped>.change-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px;margin-top:18px}.change-json{white-space:pre-wrap;background:#f6f8fa;padding:14px;border-radius:8px;line-height:1.8}</style>
